# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 797)
        MainWindow.setStyleSheet("background-color: rgb(22, 22, 23);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, 7, -1, -1)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 4, 2)
        spacerItem = QtWidgets.QSpacerItem(684, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.modeSwitch = QtWidgets.QToolButton(self.centralwidget)
        self.modeSwitch.setMinimumSize(QtCore.QSize(35, 35))
        self.modeSwitch.setStyleSheet("QToolButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QToolButton::Hover{\n"
"background-color: rgb(245, 245, 245);\n"
"}")
        self.modeSwitch.setObjectName("modeSwitch")
        self.gridLayout.addWidget(self.modeSwitch, 0, 4, 1, 1)
        self.sidePanel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidePanel.sizePolicy().hasHeightForWidth())
        self.sidePanel.setSizePolicy(sizePolicy)
        self.sidePanel.setMinimumSize(QtCore.QSize(350, 0))
        self.sidePanel.setStyleSheet("QFrame {\n"
"background-color: rgb(22, 22, 23);\n"
"}")
        self.sidePanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidePanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidePanel.setObjectName("sidePanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidePanel)
        self.verticalLayout.setSpacing(34)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.sidePanel)
        self.title.setStyleSheet("QLabel {\n"
"font: 22pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"}")
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.progressBar = QtWidgets.QProgressBar(self.sidePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"color: rgb(22, 22, 23);\n"
"font: 10pt \"Comic Sans MS\";\n"
"text-align: right;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: rgb(2, 228, 192);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.getIndex = QtWidgets.QLineEdit(self.sidePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getIndex.sizePolicy().hasHeightForWidth())
        self.getIndex.setSizePolicy(sizePolicy)
        self.getIndex.setMinimumSize(QtCore.QSize(0, 35))
        self.getIndex.setStyleSheet("font: 10pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.getIndex.setObjectName("getIndex")
        self.horizontalLayout_2.addWidget(self.getIndex)
        self.getIndexButton = QtWidgets.QPushButton(self.sidePanel)
        self.getIndexButton.setMinimumSize(QtCore.QSize(55, 35))
        self.getIndexButton.setStyleSheet("QPushButton{\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: rgb(34, 34, 34);\n"
"border-radius: 3px;\n"
"background-color: rgb(2, 228, 192);\n"
"}\n"
"\n"
"QPushButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}")
        self.getIndexButton.setObjectName("getIndexButton")
        self.horizontalLayout_2.addWidget(self.getIndexButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.correctionsLabel = QtWidgets.QLabel(self.sidePanel)
        self.correctionsLabel.setStyleSheet("QLabel {\n"
"font: 16pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"}")
        self.correctionsLabel.setObjectName("correctionsLabel")
        self.verticalLayout.addWidget(self.correctionsLabel)
        self.removeOverlapButton = QtWidgets.QPushButton(self.sidePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeOverlapButton.sizePolicy().hasHeightForWidth())
        self.removeOverlapButton.setSizePolicy(sizePolicy)
        self.removeOverlapButton.setMinimumSize(QtCore.QSize(160, 35))
        self.removeOverlapButton.setStyleSheet("QPushButton{\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: rgb(34, 34, 34);\n"
"border-radius: 3px;\n"
"background-color: rgb(2, 228, 192);\n"
"}\n"
"\n"
"QPushButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}")
        self.removeOverlapButton.setObjectName("removeOverlapButton")
        self.verticalLayout.addWidget(self.removeOverlapButton)
        self.removeDuplicatesButton = QtWidgets.QPushButton(self.sidePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeDuplicatesButton.sizePolicy().hasHeightForWidth())
        self.removeDuplicatesButton.setSizePolicy(sizePolicy)
        self.removeDuplicatesButton.setMinimumSize(QtCore.QSize(160, 35))
        self.removeDuplicatesButton.setStyleSheet("QPushButton{\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: rgb(34, 34, 34);\n"
"border-radius: 3px;\n"
"background-color: rgb(2, 228, 192);\n"
"}\n"
"\n"
"QPushButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}")
        self.removeDuplicatesButton.setObjectName("removeDuplicatesButton")
        self.verticalLayout.addWidget(self.removeDuplicatesButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 428, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.sidePanel, 1, 0, 3, 1)
        self.topPanel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topPanel.sizePolicy().hasHeightForWidth())
        self.topPanel.setSizePolicy(sizePolicy)
        self.topPanel.setMinimumSize(QtCore.QSize(0, 180))
        self.topPanel.setStyleSheet("QFrame {\n"
"background-color: rgb(30, 30, 30);\n"
"border-radius: 8px;\n"
"}")
        self.topPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topPanel.setObjectName("topPanel")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.topPanel)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tagsPanel = QtWidgets.QFrame(self.topPanel)
        self.tagsPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tagsPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tagsPanel.setObjectName("tagsPanel")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tagsPanel)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2.addWidget(self.tagsPanel, 0, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(614, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.topPanel)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 40))
        self.toolButton.setStyleSheet("QToolButton{\n"
"font: 10pt \"Comic Sans MS\";\n"
"color: rgb(34, 34, 34);\n"
"border-radius: 3px;\n"
"background-color: rgb(2, 228, 192);\n"
"}\n"
"\n"
"QToolButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.topPanel, 2, 2, 1, 3)
        self.mainPanel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainPanel.sizePolicy().hasHeightForWidth())
        self.mainPanel.setSizePolicy(sizePolicy)
        self.mainPanel.setStyleSheet("QFrame {\n"
"background-color: rgb(30, 30, 30);\n"
"border-radius: 8px;\n"
"}")
        self.mainPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainPanel.setObjectName("mainPanel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mainPanel)
        self.gridLayout_3.setSpacing(11)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.openJsonButton = QtWidgets.QToolButton(self.mainPanel)
        self.openJsonButton.setMinimumSize(QtCore.QSize(0, 40))
        self.openJsonButton.setStyleSheet("QToolButton{\n"
"border-radius: 8px;\n"
"background-color: rgb(2, 228, 192);\n"
"font: 12pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QToolButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}")
        self.openJsonButton.setObjectName("openJsonButton")
        self.gridLayout_3.addWidget(self.openJsonButton, 1, 3, 1, 1)
        self.saveJsonButton = QtWidgets.QToolButton(self.mainPanel)
        self.saveJsonButton.setMinimumSize(QtCore.QSize(0, 40))
        self.saveJsonButton.setStyleSheet("QToolButton{\n"
"border-radius: 8px;\n"
"background-color: rgb(2, 228, 192);\n"
"font: 12pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QToolButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}")
        self.saveJsonButton.setObjectName("saveJsonButton")
        self.gridLayout_3.addWidget(self.saveJsonButton, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 3, 2, 1, 1)
        self.textSelector = QtWidgets.QTextEdit(self.mainPanel)
        self.textSelector.setStyleSheet("QTextEdit{\n"
"background-color: rgb(22, 22, 23);\n"
"border-radius: 10px;\n"
"font: 14pt \"Comic Sans MS\";\n"
"color: rgb(246, 255, 61);\n"
"padding: 15px;\n"
"selection-background-color: rgb(215, 255, 35);\n"
"selection-color: rgb(24, 24, 24);\n"
"}")
        self.textSelector.setFrameShape(QtWidgets.QFrame.Box)
        self.textSelector.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textSelector.setReadOnly(True)
        self.textSelector.setObjectName("textSelector")
        self.gridLayout_3.addWidget(self.textSelector, 0, 0, 1, 4)
        spacerItem5 = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prevButton = QtWidgets.QToolButton(self.mainPanel)
        self.prevButton.setMinimumSize(QtCore.QSize(80, 40))
        self.prevButton.setStyleSheet("QToolButton{\n"
"border-radius: 8px;\n"
"background-color: rgb(2, 228, 192);\n"
"font: 12pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QToolButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}")
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout.addWidget(self.prevButton)
        self.selectButton = QtWidgets.QToolButton(self.mainPanel)
        self.selectButton.setMinimumSize(QtCore.QSize(80, 40))
        self.selectButton.setStyleSheet("QToolButton{\n"
"border-radius: 8px;\n"
"background-color: rgb(2, 228, 192);\n"
"font: 12pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QToolButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}\n"
"\n"
"QToolButton::Checked{\n"
"background-color: rgb(1, 184, 157);\n"
"border-style: inset;\n"
"}")
        self.selectButton.setCheckable(True)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout.addWidget(self.selectButton)
        self.deselectButton = QtWidgets.QToolButton(self.mainPanel)
        self.deselectButton.setMinimumSize(QtCore.QSize(80, 40))
        self.deselectButton.setStyleSheet("QToolButton{\n"
"border-radius: 8px;\n"
"background-color: rgb(2, 228, 192);\n"
"font: 12pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QToolButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}\n"
"\n"
"QToolButton::Checked{\n"
"background-color: rgb(1, 184, 157);\n"
"border-style: inset;\n"
"}")
        self.deselectButton.setCheckable(True)
        self.deselectButton.setObjectName("deselectButton")
        self.horizontalLayout.addWidget(self.deselectButton)
        self.nextButton = QtWidgets.QToolButton(self.mainPanel)
        self.nextButton.setMinimumSize(QtCore.QSize(80, 40))
        self.nextButton.setStyleSheet("QToolButton{\n"
"border-radius: 8px;\n"
"background-color: rgb(2, 228, 192);\n"
"font: 12pt \"Comic Sans MS\";\n"
"}\n"
"\n"
"QToolButton::Hover{\n"
"background-color: rgb(1, 184, 157);\n"
"}")
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem6, 2, 3, 1, 1)
        self.gridLayout.addWidget(self.mainPanel, 3, 2, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modeSwitch.setText(_translate("MainWindow", "L"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p>NER Annotator </p><p>Editor</p></body></html>"))
        self.progressBar.setFormat(_translate("MainWindow", "%v/%m"))
        self.getIndexButton.setText(_translate("MainWindow", "Show"))
        self.correctionsLabel.setText(_translate("MainWindow", "Corrections:"))
        self.removeOverlapButton.setToolTip(_translate("MainWindow", "Removes the overlapping labels. Keeps the top label"))
        self.removeOverlapButton.setText(_translate("MainWindow", "Remove Overlaps"))
        self.removeDuplicatesButton.setToolTip(_translate("MainWindow", "Removes the overlapping labels. Keeps the top label"))
        self.removeDuplicatesButton.setText(_translate("MainWindow", "Remove Duplicates"))
        self.toolButton.setText(_translate("MainWindow", "Add Tag"))
        self.openJsonButton.setText(_translate("MainWindow", "Open JSON"))
        self.saveJsonButton.setText(_translate("MainWindow", "Save JSON"))
        self.textSelector.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans MS\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">This is some sort of text</span></p></body></html>"))
        self.prevButton.setText(_translate("MainWindow", "Prev"))
        self.selectButton.setText(_translate("MainWindow", "Select"))
        self.deselectButton.setText(_translate("MainWindow", "Deselect"))
        self.nextButton.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
