# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tagNameWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(181, 40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(166775, 60))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tagName = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagName.sizePolicy().hasHeightForWidth())
        self.tagName.setSizePolicy(sizePolicy)
        self.tagName.setMinimumSize(QtCore.QSize(80, 0))
        self.tagName.setStyleSheet("font: 12pt \"Comic Sans MS\";")
        self.tagName.setCheckable(True)
        self.tagName.setAutoRaise(True)
        self.tagName.setObjectName("tagName")
        self.horizontalLayout.addWidget(self.tagName)
        self.removeTag = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeTag.sizePolicy().hasHeightForWidth())
        self.removeTag.setSizePolicy(sizePolicy)
        self.removeTag.setMinimumSize(QtCore.QSize(0, 30))
        self.removeTag.setMaximumSize(QtCore.QSize(40, 16777215))
        self.removeTag.setStyleSheet("QPushButton{\n"
"color: rgb(255, 0, 0);\n"
"}")
        self.removeTag.setFlat(True)
        self.removeTag.setObjectName("removeTag")
        self.horizontalLayout.addWidget(self.removeTag)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tagName.setText(_translate("Form", "tag_name"))
        self.removeTag.setToolTip(_translate("Form", "<html><head/><body><p>Remove tag</p></body></html>"))
        self.removeTag.setText(_translate("Form", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
